# Generated by Django 5.1.2 on 2024-11-22 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_sector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_sector', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='sector',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profiles.business_sector'),
        ),
    ]
