# Generated by Django 5.1.2 on 2024-11-23 16:24

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_unique',
            field=models.CharField(default=profiles.models.generate_random_id, max_length=10, unique=True),
        ),
    ]
